spring:
  profiles:
    active: dev

#mybatis配置
mybatis:
  type-aliases-package: com.vienna.jaray.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 配置sql打印日志
#logging:
#  level:
#    com.vienna.jaray.mapper: debug